### ISSUE TITLE
Design choices for Asciidoc

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-rfc#28]
These are the design choices I've made for rendering RFC XML features in Asciidoc which I think are open for discussion with @paolobrasolin, as more comfortable with Asciidoc. I have to say, I'm more or less comfortable with where I have got to with these, but let's run through them.

The issue of whether normative and informative crossreferences are to be differentiated (as they are in MMark) is discussed in separate tickets. Ditto added markup on authors. (Myself, I am wary of adding machinery not built in to asciidoctor, in order to make the gem as reusable as possible, by minimising dependencies. I also don't see a strong reason why RFC Asciidoctor needs to look like MMark. But the customer is always right. :-)

* Comments:
** Are being rendered as admonitions rather than comments, since (as far as I can tell!) the asciidoctor preprocessor actually ignores native asciidoc comments. There's no option in v2 to signal that comments should be removed from a published draft, as there is in v3.

* Abstract
** Is being naively extracted as the first paragraphs after the document header and before the first section or admonitions (in the asciidoc preamble), since that is where the RFC XML schema constrains it to be. This happens whether or not there is an [abstract] style on the paragraph.

* Boilerplate
** I have not rendered v3 boilerplate in Asciidoc at all.

* Cross-reference formatting attribute
** Options of counter, title, or derived text (e.g. Table 1). I am currently ignoring these options, because xrefstyle did not seem to offer what RFC XML needed.

* iref primary attribute
** This is not whether the index term is a primary term, but whether it should be emphasised in the index as a more important reference (as boldface or italics in some book indexes). Does not seem to be supported in Asciidoc.

* author initials
** There is a clash between the Asciidoc :authorinitials attribute, which includes the initial of the surname, and the RFC XML :initials attribute, which leaves it out. For  Homer J Simpson, asciidoc would assume the authorinitials are HJS, RFC XML as HJ.  Currently I take only the initial letter of the first name as the initial. If the user can specify RFC XML initials for authors, they need to be given a name other than :authorinitials, to avoid confusion.

* referencegroups
** I have delimited groupings of references in the ulist format of references by using nested lists, but that disrupts the rendering of anchors: the default asciidoc processor clearly expects any ulist under bibliography to be flat.

* date
** Asciidoc expects an ISO date under :revdate. I currently process the date and extract out the year, month, date attributes expected by RFC XML.

* arrays in header
** MMark puts array values of header attributes in brackets, e.g. obsoletes: ["7994", "8981"]. I just leave the value as a comma-delimited list, without quotes or brackets, though that raises the possibility of ambiguity for keyword that contain commas.

* superscript, subscript
** Not natively supported at all in RFC XML v2, though they are in v3. I leave them as Latex-style ^ and _. These often end up in attribute values in v2 XML, so rendering them in markup will not always  be feasible.

* table column width
** This is more a bug, but v2 has an optional table column width attribute, which I'm reading from the colpcwidth attribute. Following the HTML5 converter, that attribute is not meant to be added if the table is autowidth, but it's being added anyway.

* Table preamble and postamble
** Not supported; any prefatory or footer free text in a table is going to be indistinguishable from a separate paragraph in Asciidoc, unless the table is embedded in  an example, say. The elements are desultorily supported in figure (example), but they are quite fragile, and the elements were justly deprecated in v3. 

* figure
** Rendered as example. Note that artwork, images, and sourcecode are all meant to be embedded within figures; the converter supplies the figure node if it is not in the Asciidoc markup.

@paolobrasolin , I suggest you have a look at the RFC Asciidoc I've created at https://github.com/riboseinc/rfc-openpgp-oscca-adoc , and let me know if you consider it idiomatic.

**Comment by ronaldtse** [comment]
@opoudjis thanks for the list! 

Here are some comments but not exhaustive since I will need some time to digest them...

### Abstract

The Abstract is a special area: citations are not allowed, and does not appear in the TOC. You can see this with the `idnits` tool that is used to validate an Internet Draft. 

I think the native asciidoctor way of putting an [abstract](http://asciidoctor.org/docs/user-manual/#user-abstract) is perfect for our purpose (using our specific `:doctype:`):
```
[abstract]
== Abstract
```

Especially since the `book` doctype also specifies requirements on the abstract
> In the book doctype, the abstract section must be a level below the chapter.


### Authors (and Author Initials)

I think it's best to separate out the XMLRFC author concept away from the AsciiDoc author concept because they are quite different (see #24). From my experience, the internet-draft "initials" are often overridden to a specific form and rarely parsed out from the actual text. 

### Reference groups

As mentioned in #26 I prefer the MMark style for separate bibliographies. This functionality could be done simply as:
* make asciidoctor-bibliography accept reference groups, and when provide a shorthand for citing documents to place them into normative/informative bibliography groups, e.g., `ncite:[RFC1234], icite:[RFC2345]`, or the MMark way `[@ABC]`, `[@!ABC]`, `[@?ABC]`.
* make asciidoctor-bibliography output bibliography separate according to their groups, e.g., `bibliography::[style=rfc,group=normative]`

### Cross References

We will need more specific forms of Cross Referencing and their rendering. For example, MMark uses `{#anchorref}` to identify and `(#anchorref)` for referencing the Section Number. Vanilla asciidoctor does not have such referencing functions, and we will need to roll our own (or as a separate gem?)


### Date

In an internet draft there is only one date, the "revision date". So that fits in nicely with `:revdate` which can be set independently as a document attribute or in the document header short hand like `[revnum], [revdate]`. `revdate` also accepts dates like "2017-10-03", so the key is just parsing it according to Ruby DateTime.

### Arrays as Lists in header

Should be totally fine, these include the `updates` list and the `obsoletes` list.

**Comment by opoudjis** [comment]
Immediate action: I'm introducing a distinct `forename_initials` attribute to replace the Asciidoctor "initials" attribute: that is what will be parsed by the gem.
