### ISSUE TITLE
BCP14 rendering output in v3 vs v2

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#43]
In the README it says `v3: <bcp14>MUST NOT</bcp14>. Not supported in v2.`

Should be `v3: <bcp14>MUST NOT</bcp14>. Rendered as inline text "MUST NOT" in v2.`

@opoudjis could you confirm that v2 does render them? Thanks!

**Comment by opoudjis** [comment]
The ticket on what to do with these is still pending. The [bcp14] macro is currently not processed in v2, so the text will just flow through; I can make it process them and capitalise them in v2. 

Still pending is to find a shorter macro than [bcp14]. What I can do is have a document flag :bold_bcp14 , and if that flag is on, then any boldface BCP14 text will be converted in bcp14 markup. That is essentially the MMark solution, we can make it opt-in or opt-out (because there may be contexts where you want to boldface a MUST without it being a BCP14 text.)

What say you?

**Comment by ronaldtse** [comment]
@opoudjis I think the MMark shorthand converting "bold" to BCP14 keywords is fine, so in asciidoc we can use `*MUST*` to represent BCP14 `MUST`.

You're right that sometimes a "must" is not a BCP14 "MUST", as described here https://tools.ietf.org/html/rfc8174. However it would be rare (and probably bad practice) that in an RFC one wants to bold a normal "must".

We could have a flag to opt-out, like `:rfc-bold-bcp14`.

At least we have this settled! 👍

**Comment by opoudjis** [comment]
Implemented. Refer spec: opt-out flag for bold uppercase BCP14 words is `:no-rfc-bold-bcp14:`. `[bcp14]#X#` is respected in v2.

**Comment by ronaldtse** [comment]
Awesome thanks @opoudjis !
