### ISSUE TITLE
Smart apostrophes

### ISSUE THREAD

**Issue by opoudjis** [riboseinc/asciidoctor-rfc#57]
Asciidoctor natively converts apostrophes (as opposed to single quotes) to smart apostrophes; e.g. `don't` is rendered as `don‘t`. This is not necessarily a good thing for XML output. Nor should we be forcing users to escape apostrophes as `don\'t`.

@ronaldtse, should I undo smart apostrophes in the RFC XML output?

**Comment by ronaldtse** [comment]
I do not know the answer to this.

Since RFC XML v3 is working towards allowing Unicode RFCs for translated or non-ASCII RFCs, maybe this sort of thing is actually what they want? There is no XML2RFC v3 yet so we don't know if it will parse these symbols correctly.

However in v2, we should probably undo them since XML2RFC v2 probably doesn't support smart apostrophes.

**Comment by opoudjis** [comment]
I'm making this another document option: `:smart-apostrophes:`, default false. Adding also `:smart-quotes` document  option.

**Comment by opoudjis** [comment]
Collapsing them into a single `:smart-quotes` option.
