### ISSUE TITLE
Inconsistent behavior of `[source]` block without figure wrapper in v3/v2

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#84]
The README states that:
> sourcecode (v3) and artwork (v2) elements only occur within a figure wrapper; this gem supplies that wrapper if it is not provided explicitly.

However, when I do not supply the figure wrapper like this:

```
[[id]]
.Source code listing title
[source,asciidoc]
----
= My title
----
```

It says the `reference 'id' is not found`. I suspect the gem is not creating the figure wrapper in v2. I know somewhere in a later paragraph it says "v2: explicit wrapper" required", but could we supply the figure wrapper automatically?

Thanks!

**Comment by opoudjis** [comment]
Ah. What's happening is, it's supplying the wrapper, but it's not moving the ID of the source code snippet up to be the ID of the figure wrapper; and because RFC XML v2 doesn't support IDs on source code snippets, the ID doesn't show up anywhere.

I considered promoting the ID into the wrapper, and rejected it, because it would be a different level of ID from what the source provide. But that is being pedantic. In v2, I will move the ID from the snippet to the wrapper. I won't in v3, because snippet IDs are supported there.

**Comment by ronaldtse** [comment]
Got it, once it's fixed could you also help update the README (v2/v3)? Thanks @opoudjis !

**Comment by opoudjis** [comment]
Done
