### ISSUE TITLE
Handling IRTF Working Groups

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/asciidoctor-rfc#89]
Technically, "IRTF" documents should have "submission-type" "IRTF", and "workgroup" the name of an IRTF working group. However, the list of working groups now don't include them.

IRTF Groups can be found here: https://irtf.org/groups . We should accept abbreviations and also the full names of them.

From #85.

**Comment by opoudjis** [comment]
I have not done the groups under consideration for chartering in https://datatracker.ietf.org/group/chartering/ , because their HTML is less slurpable, and because it's not clear to me that those groups would have I.D's being authored against them anyway.

Otherwise, IRTF groups now also being screenscraped.
